Introduction to Machine Learning 

By Andreas C Muller & Sarah Guido

# Chapter 1: Introduction

## Why Machine Learning

## Why Python?

## scikit-learn

## Essential Libraries and Tools

## Python 2 Versus Python 3

## Versions Used in this book

In [8]:
import sys
print("My Python Version:", sys.version)
print("Book Python Version: 3.7.0 Jun 28, 2018\n")


import pandas as pd 
print("Pandas Version:", pd.__version__)
print("Pandas Version: 0.23.4\n")

import matplotlib
print('matplotlib Version:', matplotlib.__version__)
print('matplotlib Version:3.0.0\n')

import numpy as np
print("numpy Version:", np.__version__)
print("numpy Version: 1.15.2\n")

import scipy as sp
print("scipy Version:", sp.__version__)
print("scipy Version: 1.1.0\n")

import IPython
print("IPython Version:", IPython.__version__)
print("IPython Version: 6.4.0\n")

import sklearn
print("scikit-learn Version:", sklearn.__version__)
print("scikit-learn Version: 0.20.0\n")
0

My Python Version: 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)]
Book Python Version: 3.7.0 Jun 28, 2018

Pandas Version: 2.2.2
Pandas Version: 0.23.4

matplotlib Version: 3.9.0
matplotlib Version:3.0.0

numpy Version: 2.0.0
numpy Version: 1.15.2

scipy Version: 1.13.1
scipy Version: 1.1.0

IPython Version: 8.25.0
IPython Version: 6.4.0

scikit-learn Version: 1.5.0
scikit-learn Version: 0.20.0



0

## A First Application: Classifying Iris Species

### Meet the Data

In [9]:
from sklearn.datasets import load_iris
iris_dataset = load_iris() # This is a Bunch object, similar to a dictionary

print("Keys of iris_dataset:\n", iris_dataset.keys())

Keys of iris_dataset:
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


The value of the key DESCR is a short description of the dataset. 

In [10]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

The value of the key target _names is an array of strings, containing the species of flower that we want to predict:

In [11]:
print('Target names:', iris_dataset['target_names'])

Target names: ['setosa' 'versicolor' 'virginica']


The value of feature_names is a list of strings, giving the description of each feature:

In [12]:
print("Feature name:\n", iris_dataset['feature_names'])

Feature name:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


The data itself is contained in the target and data firlds. Data contains the numeric measurements of sepal length, sepal width, petal length, and petal width in a numpy array:

In [13]:
print("Type of data:", type(iris_dataset['data']))

Type of data: <class 'numpy.ndarray'>


The rows in the data array correspond to flowers, while the columns represent the four measurements that were taken for each flower.

In [17]:
print("Shape of data:\n", iris_dataset['data'].shape)
print("\n", iris_dataset['data'])


Shape of data:
 (150, 4)

 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.

The array contains 150 different flowers. (page 16)

Test